name: Gitnu
description: A Chrome packaged application providing a terminal interface for Git. Git interactive terminal, not unix
dependencies:
  archive: 1.0.6
  browser: any
  chrome_gen: any
  crc32: any
  crypto: any
  unittest: any
  utf: any
